# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99b35e52be56ac227290d5b2818439ba30a792635fcfee619b4b37d8866521cd3e3a4116c597d080559fc335db67164aa97bb16be84e2c2b2512ed038354446

test:
  secret_key_base: d1130749f6bb6bba8ab0121da5ef4a1dd40e4f9f306e7ade56ba46f4d8e49492e93f6e5ca4dfe235e83fd49a64a31fd7e56bbc22f988e3d12c2556be133527fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
